using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject.Extensions.WeakEventMessageBroker: Weak event message broker extension fo" +
    "r Ninject")]
[assembly: AssemblyCompanyAttribute("Innovatian Software, LLC")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2008-2010 Innovatian Software, LLC and contributors")]
[assembly: AssemblyVersionAttribute("2.1.0.10")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

